# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leakwatch < Formula
  desc "High-performance secret scanner for codebases, Git histories, and container images"
  homepage "https://github.com/HodeTech/Leakwatch"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.6.0/leakwatch_1.6.0_darwin_amd64.tar.gz"
      sha256 "2b96ad227edbd12c68bf4a4b72b420f07e31465e4aa7134d84e0631e5ae6f51d"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.6.0/leakwatch_1.6.0_darwin_arm64.tar.gz"
      sha256 "175df35fa0913dc432e27d477afec806ac3b15ae8d00382f230fa58bad82f5f8"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.6.0/leakwatch_1.6.0_linux_amd64.tar.gz"
      sha256 "f1c6a652d0ff8040b7826daf7c21f8fef7f1a98bd28b2d5b6e7e95833da9a9fc"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.6.0/leakwatch_1.6.0_linux_arm64.tar.gz"
      sha256 "1a914f15590ea4d8728d2f95388a5ff35e6bdd909fc7712a4e131c74e73398fe"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  test do
    system "#{bin}/leakwatch", "version"
  end
end
