# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leakwatch < Formula
  desc "High-performance secret scanner for codebases, Git histories, and container images"
  homepage "https://github.com/HodeTech/Leakwatch"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.6.0/leakwatch_1.6.0_darwin_amd64.tar.gz"
      sha256 "73544f217da1eca91e5a4a21ba3d2f3a72ece54d74300c48cc50941a162d9ec7"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.6.0/leakwatch_1.6.0_darwin_arm64.tar.gz"
      sha256 "71ee6c969564136ab3295db8e7408f2dba22c80fc98b324aed38783c420fa79f"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.6.0/leakwatch_1.6.0_linux_amd64.tar.gz"
      sha256 "fb0587882caaebe7eddaa52376119bab80d489e4e7122518bc04ca3c57a4d589"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.6.0/leakwatch_1.6.0_linux_arm64.tar.gz"
      sha256 "9737f06319d26e8e9b24e484ef47631d67e544b4f7a765f6e6e628815320dfad"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  test do
    system "#{bin}/leakwatch", "version"
  end
end
