# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leakwatch < Formula
  desc "High-performance secret scanner for codebases, Git histories, and container images"
  homepage "https://github.com/HodeTech/Leakwatch"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.7.0/leakwatch_1.7.0_darwin_amd64.tar.gz"
      sha256 "66a5d7ebe2e7425e378f1261ec74fbf425a883555484375ed73e309987fcf468"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.7.0/leakwatch_1.7.0_darwin_arm64.tar.gz"
      sha256 "952279d08cf23b6d7b41f865cc5cead401bd8adb8ef7d92d0767652d6724e022"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.7.0/leakwatch_1.7.0_linux_amd64.tar.gz"
      sha256 "719f6df5c56de84691deccff627c33958dd2216b22d93b78db10a29d24214e32"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HodeTech/Leakwatch/releases/download/v1.7.0/leakwatch_1.7.0_linux_arm64.tar.gz"
      sha256 "3c511632246616527a746db6ac5420a93a8df3848d46c2eb4f188058fc912482"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  test do
    system "#{bin}/leakwatch", "version"
  end
end
